# Default values for claims-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  name: claims-api

image:
  repository: csulabtest.azurecr.io/claims-api
  tag: 278
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

checks:
  initialDelay: 10
  periodSeconds: 30

ingress:
  enabled: false
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

azureIdentityBinding:
  selector: claims-api-kv-mid

kv:
  name: claims-api-kv
  secretName: sqldbconn
  # Multiple object types can be specified separated by commas.
  objectTypes: secret
  resourceGroup: csu-dev-grts-rg10
  subscriptionId: f99e3e10-4fe2-476a-bf9c-e2e1be9e7a53
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
